"""
Presentation Planner for CogniShift.
Translates user requirements, retrieved evidence, and canonical workspace artifacts
into structured PresentationSpecs using deterministic pagination and layout policies.
"""
import re
from typing import List, Dict, Any, Optional, Union
from cognishift.core.presentation.schemas import (
    PresentationSpec,
    SlideSpec,
    SlideType,
    ThemeName,
    MetricCard
)


class PresentationPlanner:
    """
    Constructs a validated PresentationSpec following the principle:
    'LLM / Planner decides WHAT, Renderer decides HOW; Pagination over shrinking.'
    """

    @classmethod
    def plan_presentation(
        cls,
        title: str,
        goal: str,
        evidence_snippets: List[str],
        source_citations: List[str],
        image_artifact_ids: Optional[List[int]] = None,
        chart_artifact_ids: Optional[List[int]] = None,
        metrics: Optional[List[Dict[str, str]]] = None,
        table_data: Optional[Dict[str, Any]] = None,
        theme: ThemeName = ThemeName.EXECUTIVE,
        recommendations: Optional[List[str]] = None,
        speaker_notes_map: Optional[Dict[int, str]] = None
    ) -> PresentationSpec:
        slides: List[SlideSpec] = []
        image_ids = image_artifact_ids or []
        chart_ids = chart_artifact_ids or []
        speaker_notes = speaker_notes_map or {}

        # 1. Title Slide
        clean_title = title.strip() if title else "Executive Operations Brief"
        if len(clean_title) > 80:
            clean_title = clean_title[:77] + "..."

        subtitle = f"Automated Engineering Analysis — {goal[:70]}" if goal else "CogniShift Sovereign Workbench"
        slides.append(
            SlideSpec(
                slide_type=SlideType.TITLE,
                title=clean_title,
                subtitle=subtitle,
                speaker_notes=speaker_notes.get(1, "Executive briefing presentation generated by CogniShift.")
            )
        )

        # 2. Executive Summary / Problem Statement
        exec_bullets = []
        if evidence_snippets:
            for snip in evidence_snippets[:4]:
                line = snip.strip().replace("\n", " ")
                if len(line) > 120:
                    line = line[:117] + "..."
                exec_bullets.append(line)
        else:
            exec_bullets.append(f"Incident Investigation & Diagnostic Summary for {goal[:60]}.")

        slides.append(
            SlideSpec(
                slide_type=SlideType.EXECUTIVE_SUMMARY,
                title="Executive Incident Summary",
                subtitle="High-Level Operational Status & Immediate Findings",
                bullets=exec_bullets,
                source_refs=source_citations[:3],
                speaker_notes=speaker_notes.get(2, "Key incident observations from validated telemetry and manual data.")
            )
        )

        # 3. Key Metrics / KPIs Slide (if provided)
        if metrics:
            metric_cards = []
            for m in metrics[:4]:
                metric_cards.append(
                    MetricCard(
                        label=m.get("label", "Metric"),
                        value=m.get("value", "N/A"),
                        subtext=m.get("subtext"),
                        status=m.get("status", "NORMAL")
                    )
                )
            slides.append(
                SlideSpec(
                    slide_type=SlideType.METRIC_KPI,
                    title="Critical Operating Parameters",
                    subtitle="Sensor Setpoints and Real-Time Variance",
                    metrics=metric_cards,
                    speaker_notes="Instrument telemetry values corroborating plant operating state."
                )
            )

        # 4. Chart / Trend Slide (if charts provided)
        for idx, c_id in enumerate(chart_ids, start=1):
            slides.append(
                SlideSpec(
                    slide_type=SlideType.CHART,
                    title="Telemetry & Parameter Trends",
                    subtitle="Quantitative Excursion Timeline",
                    chart_artifact_ids=[c_id],
                    source_refs=source_citations[:2],
                    speaker_notes="Verified time-series trend data from plant historians."
                )
            )

        # 5. Table Data Slide (if table provided)
        if table_data and "headers" in table_data and "rows" in table_data:
            # Enforce max 8 rows per slide for readability (pagination over shrinking)
            raw_rows = table_data.get("rows", [])
            CHUNK_SIZE = 8
            if len(raw_rows) <= CHUNK_SIZE:
                slides.append(
                    SlideSpec(
                        slide_type=SlideType.TABLE,
                        title="Engineering Data & Thresholds",
                        subtitle="Detailed Parameter Log",
                        table=table_data,
                        source_refs=source_citations[:2],
                        speaker_notes="Tabular setpoints and verification values."
                    )
                )
            else:
                for chunk_idx, i in enumerate(range(0, len(raw_rows), CHUNK_SIZE), start=1):
                    sub_rows = raw_rows[i:i + CHUNK_SIZE]
                    slides.append(
                        SlideSpec(
                            slide_type=SlideType.TABLE,
                            title=f"Engineering Data & Thresholds (Part {chunk_idx})",
                            subtitle=f"Parameter Log rows {i+1} to {min(i+len(sub_rows), len(raw_rows))}",
                            table={"headers": table_data["headers"], "rows": sub_rows},
                            source_refs=source_citations[:2]
                        )
                    )

        # 6. Diagram / Image Slide (if images provided)
        for idx, img_id in enumerate(image_ids, start=1):
            slides.append(
                SlideSpec(
                    slide_type=SlideType.IMAGE_WITH_EXPLANATION,
                    title="Schematic & Piping Layout",
                    subtitle="P&ID Visual Substrate Inspection",
                    image_artifact_ids=[img_id],
                    source_refs=source_citations[:2],
                    speaker_notes="P&ID engineering blueprint confirming equipment tag coordinates."
                )
            )

        # 7. Recommended Actions Slide (if recommendations provided)
        recs = recommendations or [
            "Conduct physical inspection of primary isolation valve XV-101 seat integrity.",
            "Recalibrate pressure transmitter PT-101 in accordance with ASME Section VIII Division 1.",
            "Verify dual supervisor authorization log prior to restart authorization."
        ]
        # Pagination over shrinking: max 5 bullets per slide
        MAX_BULLETS = 5
        if len(recs) <= MAX_BULLETS:
            slides.append(
                SlideSpec(
                    slide_type=SlideType.RECOMMENDED_ACTIONS,
                    title="Corrective & Preventive Actions (CAPA)",
                    subtitle="Prioritized Engineering Recommendations",
                    bullets=recs,
                    speaker_notes="Recommended next steps for engineering and operations supervisors."
                )
            )
        else:
            for part_idx, i in enumerate(range(0, len(recs), MAX_BULLETS), start=1):
                slides.append(
                    SlideSpec(
                        slide_type=SlideType.RECOMMENDED_ACTIONS,
                        title=f"Corrective Actions (Part {part_idx})",
                        subtitle="Prioritized Engineering Recommendations",
                        bullets=recs[i:i + MAX_BULLETS],
                        speaker_notes="Recommended next steps for engineering and operations supervisors."
                    )
                )

        # 8. Mandatory Source Appendix Slide
        unique_sources = list(dict.fromkeys(source_citations))
        if not unique_sources:
            unique_sources = ["Plant DCS SCADA Historian", "OISD-STD-152 Compliance Manual"]

        slides.append(
            SlideSpec(
                slide_type=SlideType.SOURCE_APPENDIX,
                title="Authoritative Source Citations",
                subtitle="Verified Sovereign Knowledge Ledger",
                bullets=unique_sources,
                speaker_notes="Auditable references and data provenance citations."
            )
        )

        return PresentationSpec(
            title=clean_title,
            subtitle=subtitle,
            theme=theme,
            slides=slides,
            sources=unique_sources
        )

    @classmethod
    def plan_investigation_deck(
        cls,
        title: str,
        subtitle: Optional[str],
        goal: str,
        theme: ThemeName = ThemeName.EXECUTIVE,
        metrics: Optional[List[MetricCard]] = None,
        timeline_events: Optional[List[Dict[str, str]]] = None,
        evidence_bullets: Optional[List[str]] = None,
        topology_left: Optional[List[str]] = None,
        topology_right: Optional[List[str]] = None,
        topology_image_artifact_ids: Optional[List[Union[int, str]]] = None,
        chart_artifact_ids: Optional[List[Union[int, str]]] = None,
        chart_takeaways: Optional[List[str]] = None,
        root_causes: Optional[List[str]] = None,
        uncertainties: Optional[List[str]] = None,
        recommendations: Optional[List[str]] = None,
        sources: Optional[List[str]] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> PresentationSpec:
        """
        Production planner for comprehensive 10-slide incident investigation and RCA decks.
        Constructs grounded SlideSpecs without arbitrary x/y coordinates from evidence.
        """
        slides: List[SlideSpec] = []

        # Slide 1: Title
        final_subtitle = subtitle or "Incident Investigation & Engineering Review"
        if metadata and metadata.get("is_synthetic_demo"):
            if "synthetic demonstration" not in final_subtitle.lower() and "demonstration scenario" not in final_subtitle.lower():
                final_subtitle = f"{final_subtitle} | DEMONSTRATION SCENARIO — SYNTHETIC DEMONSTRATION DATA"
        slides.append(
            SlideSpec(
                slide_type=SlideType.TITLE,
                title=title,
                subtitle=final_subtitle,
                required_elements=["title", "subtitle"]
            )
        )

        # Slide 2: Executive Summary (with top KPI cards + grounded findings)
        exec_bullets = evidence_bullets[:5] if evidence_bullets else [
            f"Automated forensic investigation initiated for {goal[:80]}."
        ]
        slides.append(
            SlideSpec(
                slide_type=SlideType.EXECUTIVE_SUMMARY,
                title="Executive Summary: Overpressure Excursion",
                subtitle="High-Level Finding, Threshold Breach & Safe Operating Limits",
                bullets=exec_bullets,
                metrics=metrics or [],
                required_elements=["metrics", "key_findings"]
            )
        )

        # Slide 3: Incident Timeline (Milestones)
        tl_items = timeline_events or [
            {"timestamp": "08:14:00 UTC", "event": "Steady state operations baseline."},
            {"timestamp": "08:14:25 UTC", "event": "High pressure alarm trip activated."},
            {"timestamp": "08:14:32 UTC", "event": "Peak overpressure excursion reached."},
            {"timestamp": "08:14:45 UTC", "event": "Unit depressurized after delayed isolation."}
        ]
        slides.append(
            SlideSpec(
                slide_type=SlideType.TIMELINE,
                title="Sequence of Events (2026-08-14)",
                subtitle="High-Resolution Chronology of Alarms, Valve Dynamics, and Pressure Excursion",
                timeline_items=tl_items,
                required_elements=["timeline_items"]
            )
        )

        # Slide 4: Multi-Channel Evidence Synthesis
        slides.append(
            SlideSpec(
                slide_type=SlideType.EVIDENCE_SUMMARY,
                title="Multi-Channel Evidence Synthesis",
                subtitle="Cross-Document Verification Across Telemetry, SOPs, Inspection Reports & P&IDs",
                bullets=evidence_bullets or [
                    "SCADA Telemetry proves rapid pressure rise crossing ASME Section VIII thresholds.",
                    "SOP Maintenance standard mandates 30s emergency valve stroke time.",
                    "NDT Metallurgical report confirms mechanical binding and adhesive galling.",
                    "Historical board review documented prior actuator warnings."
                ],
                required_elements=["evidence_observations"]
            )
        )

        # Slide 5: Process Topology & Isolation. Use a grounded visual only when
        # the caller has already resolved and registered a compatible artifact.
        topology_visual_ids = topology_image_artifact_ids or []
        slides.append(
            SlideSpec(
                slide_type=SlideType.IMAGE_WITH_EXPLANATION if topology_visual_ids else SlideType.TWO_COLUMN,
                title="Plant P&ID & Process Isolation Topology",
                subtitle="Line Routing, Emergency Valve Interlocks & Safeguard Verification",
                bullets=(topology_right if topology_visual_ids else topology_left) or ["Accumulator Vessel V-101 overhead stream isolated via XV-101."],
                column_right=topology_right or ["Primary Safeguard: Valve XV-101 closure."],
                image_artifact_ids=topology_visual_ids,
                required_elements=["chart_artifact_id", "takeaways"] if topology_visual_ids else ["left_column", "right_column"]
            )
        )

        # Slide 6: Telemetry Excursion Chart
        takeaways = chart_takeaways or [
            "High pressure alarm annunciated at 08:14:25 (42.8 barg).",
            "Pressure breached ASME design limit at 08:14:30 (45.3 barg).",
            "Peak excursion occurred at 08:14:32 (46.8 barg).",
            "Depressuring commenced upon delayed seating of XV-101."
        ]
        slides.append(
            SlideSpec(
                slide_type=SlideType.CHART,
                title="Telemetry Excursion vs Design Setpoint",
                subtitle="Real-Time PT-101 Sensor Trace Against ASME VIII 45.0 barg Design Threshold",
                chart_artifact_ids=chart_artifact_ids or ["pressure_trend_canonical.png"],
                bullets=takeaways,
                required_elements=["chart_artifact_id", "takeaways"]
            )
        )

        # Slide 7: Root Cause Determination
        rc_items = root_causes or [
            "Primary Physical Cause: Severe stem galling on actuator linkage of suction valve XV-101.",
            "Direct Consequence: Closure delay of 38.4s (8.4s beyond the 30.0s safety baseline).",
            "Contributing Factor: Uneven gland torque causing stem lateral binding.",
            "Systemic Factor: 90-day deferral of scheduled quarterly lubrication in SAP PM #400192."
        ]
        slides.append(
            SlideSpec(
                slide_type=SlideType.ROOT_CAUSE,
                title="Root Cause Determination: Valve Mechanical Binding",
                subtitle="Engineering Failure Analysis, Contributing Physical Factors & Maintenance History",
                bullets=rc_items,
                required_elements=["root_causes"]
            )
        )

        # Slide 8: Uncertainty & Verification Gaps
        unc_items = uncertainties or [
            "Acoustic survey of relief valve RV-101 seat tightness remains pending startup.",
            "Thermal fatigue crack inspection on HEX-102 tube sheet requires radiography.",
            "Deadweight verification of transmitter PT-101 calibration curve in progress.",
            "Actuator motor drive current logs from MCC need extraction to confirm trip torque.",
            "No structural deformation identified on V-101 shell or nozzle welds."
        ]
        slides.append(
            SlideSpec(
                slide_type=SlideType.BULLETS,
                title="Uncertainty Analysis & Verification Gaps",
                subtitle="Identified Unknowns, Uninspected Components & Verification Requirements",
                bullets=unc_items,
                required_elements=["uncertainties"]
            )
        )

        # Slide 9: Recommended Actions (CAPA)
        capa_items = recommendations or [
            "Immediate: Complete overhaul of XV-101 actuator, replace stem and guide bushing.",
            "Immediate: Recalibrate transmitter PT-101 and re-verify 45.0 barg trip logic in DCS.",
            "Pre-Startup: Conduct dynamic full-stroke test to verify closure time <= 30.0 seconds.",
            "Preventative: Establish strict zero-deferral policy on quarterly safety valve lubrication.",
            "Governance: Mandate dual-supervisor signoff for any PM schedule changes on critical SIS valves."
        ]
        slides.append(
            SlideSpec(
                slide_type=SlideType.RECOMMENDED_ACTIONS,
                title="Mandatory Corrective & Preventative Actions",
                subtitle="Prioritized Engineering Interventions, Governance Upgrades & Pre-Startup Criteria",
                bullets=capa_items,
                required_elements=["recommendations"]
            )
        )

        # Slide 10: Authoritative Source Appendix
        src_items = sources or [
            "Inspection_Report.pdf | Page 1 & 2 | Ultrasonic Thickness & Actuator Inspection",
            "Plant_PID.pdf | Page 1 | Unit 100 Crude Overhead P&ID Drawing DWG-PID-U100-01",
            "Telemetry.xlsx | Rows 1-30 | SCADA Telemetry Stream PT-101 / TT-201",
            "Maintenance_SOP.docx | Section: 2 | Transmitter Calibration Thresholds",
            "Previous_Board_Review.pptx | Slide 2 | Historical Actuator Vulnerabilities & Notes"
        ]
        slides.append(
            SlideSpec(
                slide_type=SlideType.SOURCE_APPENDIX,
                title="Authoritative Knowledge Sources & Provenance",
                subtitle="Auditable Reference Ledger Across Heterogeneous Enterprise Artifacts",
                sources=src_items,
                required_elements=["sources"]
            )
        )

        return PresentationSpec(
            title=title,
            subtitle=subtitle,
            theme=theme,
            slides=slides,
            sources=src_items,
            metadata=metadata or {}
        )
