"""
Hostile Output Validation and Safe Artifact Promotion.
Validates outputs generated inside /workspace/output and safely promotes valid deliverables
into the immutable Phase 3 workspace_artifacts registry.
"""
import shutil
import logging
from pathlib import Path
from typing import List, Tuple, Dict, Any

from cognishift.app.config import settings
from cognishift.core.artifact_generators import (
    validate_artifact_structure,
    create_and_register_artifact
)

logger = logging.getLogger(__name__)

# Permitted deliverable extensions eligible for artifact promotion
ALLOWED_OUTPUT_EXTENSIONS = {
    ".txt": "txt",
    ".csv": "csv",
    ".json": "json",
    ".docx": "docx",
    ".xlsx": "xlsx",
    ".pptx": "pptx"
}

# Strictly prohibited executable extensions that must NEVER be promoted
PROHIBITED_OUTPUT_EXTENSIONS = {
    ".py", ".pyc", ".sh", ".bash", ".ps1", ".bat", ".cmd",
    ".exe", ".dll", ".so", ".bin", ".tar", ".gz", ".zip"
}


async def validate_and_promote_outputs(
    workspace_id: int,
    run_id: int,
    execution_id: str,
    output_dir: Path
) -> Tuple[List[str], List[int]]:
    """
    Scans and hostile-validates all outputs in /workspace/output:
    1. Rejects symlinks, hardlinks, FIFOs, and special devices.
    2. Validates output count, per-file size, and aggregate size limits.
    3. Rejects executable file types (.py, .sh, .exe, etc.).
    4. Validates office documents via structural validators.
    5. Promotes valid files using Phase 3 atomic create_and_register_artifact pipeline.
    
    Returns:
        Tuple of (promoted_filenames, promoted_artifact_ids)
    """
    if not output_dir.exists():
        return [], []

    promoted_names: List[str] = []
    promoted_ids: List[int] = []

    # Collect all items in output directory
    items = list(output_dir.iterdir())
    if len(items) > settings.sandbox_max_output_files:
        logger.warning(
            f"Sandbox execution {execution_id} produced {len(items)} files, "
            f"exceeding maximum limit of {settings.sandbox_max_output_files}."
        )
        items = items[:settings.sandbox_max_output_files]

    total_bytes = 0

    for item in items:
        # 1. Reject directories and special filesystem objects (symlinks, junctions, fifos)
        try:
            if item.is_symlink() or not item.is_file():
                logger.warning(f"Rejecting non-regular/symlinked output file: {item.name}")
                continue
            file_size = item.stat().st_size
        except OSError as e:
            logger.warning(f"Rejecting inaccessible/symlinked output item {item.name}: {e}")
            continue

        if file_size > settings.sandbox_max_output_file_bytes:
            logger.warning(
                f"Rejecting oversized output file {item.name}: {file_size} bytes exceeds limit of {settings.sandbox_max_output_file_bytes}."
            )
            continue

        total_bytes += file_size
        ext = item.suffix.lower()

        # 2. Reject prohibited executables
        if ext in PROHIBITED_OUTPUT_EXTENSIONS:
            logger.warning(f"Security: Refusing to promote executable/script output: {item.name}")
            continue

        # 3. Check allowed extensions
        if ext not in ALLOWED_OUTPUT_EXTENSIONS:
            logger.info(f"Skipping non-deliverable output extension: {item.name}")
            continue

        artifact_type = ALLOWED_OUTPUT_EXTENSIONS[ext]

        # 4. For structured documents, run structural validation
        if artifact_type in ["docx", "xlsx", "pptx"]:
            val_res = validate_artifact_structure(item, artifact_type)
            if not val_res.valid:
                logger.warning(f"Structural validation failed for {item.name}: {val_res.error_message}")
                continue

        # 5. Safe promotion via Phase 3 atomic registration pipeline
        safe_filename = item.name

        def copy_generator(dest_path: Path):
            shutil.copy2(str(item), str(dest_path))

        try:
            art_record = await create_and_register_artifact(
                workspace_id=workspace_id,
                filename=safe_filename,
                artifact_type=artifact_type,
                generator_fn=copy_generator,
                title=f"Sandbox Deliverable: {safe_filename}",
                description=f"Generated by sandbox execution {execution_id}",
                metadata={"execution_id": execution_id, "promoted_from_sandbox": True},
                run_id=run_id
            )
            art_id = art_record["id"] if isinstance(art_record, dict) else art_record.id
            promoted_names.append(safe_filename)
            promoted_ids.append(art_id)
            logger.info(f"Promoted sandbox deliverable #{art_id}: '{safe_filename}'")
        except Exception as e:
            logger.error(f"Failed to promote sandbox output '{safe_filename}': {e}")

    return promoted_names, promoted_ids
