import { useEffect, useState } from "react";
import { artifactsApi } from "@/api/artifacts";
import { ApiError } from "@/api/clients";
import { Button } from "@/components/ui/Button";
import { IconArchive, IconDownload } from "@/components/ui/Icon";
import { PageHeader } from "@/components/PageHeader";
import { Panel, PanelBody, PanelHeader } from "@/components/ui/Panel";
import { EmptyState, ErrorState, InlineError, LoadingState } from "@/components/ui/States";
import { useWorkspaces } from "@/context/useWorkspaces";
import { formatBytes, formatDateTime, titleCase } from "@/lib/format";
import type { Artifact } from "@/types";

export function ArtifactsPage() {
  const { selectedWorkspaceId, selectedWorkspace } = useWorkspaces();
  const [artifacts, setArtifacts] = useState<Artifact[]>([]);
  const [total, setTotal] = useState(0);
  const [searchQuery, setSearchQuery] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [downloadingId, setDownloadingId] = useState<number | null>(null);
  const [downloadError, setDownloadError] = useState<string | null>(null);

  useEffect(() => {
    if (!selectedWorkspaceId) {
      setArtifacts([]);
      setLoading(false);
      return;
    }
    let cancelled = false;
    setLoading(true);
    setError(null);
    artifactsApi
      .list(selectedWorkspaceId)
      .then((res) => {
        if (cancelled) return;
        setArtifacts(res.artifacts);
        setTotal(res.total);
      })
      .catch((err) => {
        if (!cancelled) setError(err instanceof Error ? err.message : "Failed to load artifacts.");
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [selectedWorkspaceId]);

  async function handleDownload(artifact: Artifact) {
    if (!selectedWorkspaceId) return;
    setDownloadingId(artifact.id);
    setDownloadError(null);
    try {
      await artifactsApi.download(selectedWorkspaceId, artifact.id, artifact.filename);
    } catch (err) {
      setDownloadError(err instanceof ApiError ? err.message : "Download failed.");
    } finally {
      setDownloadingId(null);
    }
  }

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="Artifacts"
        description={
          selectedWorkspace
            ? `Files generated by agent runs in ${selectedWorkspace.name} — reports, spreadsheets, and other run outputs.`
            : "Files generated by agent runs."
        }
      />

      {downloadError && <InlineError message={downloadError} />}

      {!selectedWorkspaceId ? (
        <EmptyState title="Select a workspace" description="Choose a workspace from the top bar to browse its artifacts." />
      ) : (
        <Panel>
          <PanelHeader
            icon={<IconArchive className="h-3.5 w-3.5" />}
            title="Generated Files"
            meta={<span className="font-mono text-[10px] text-ink-3">{total}</span>}
          />
          <PanelBody className="p-0">
            {artifacts.length > 0 && (
              <div className="border-b border-surface-border bg-surface-2/30 p-2.5">
                <input
                  type="text"
                  placeholder="Search deliverables by filename, title, or Run #…"
                  className="input w-full text-xs font-mono"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                />
              </div>
            )}
            {loading ? (
              <LoadingState />
            ) : error ? (
              <ErrorState message={error} />
            ) : artifacts.length === 0 ? (
              <EmptyState
                icon={<IconArchive className="h-6 w-6" />}
                title="No artifacts yet"
                description="Artifacts appear here when an agent run produces a generated file (report, spreadsheet, document)."
              />
            ) : (
              <ul className="divide-y divide-surface-border">
                {artifacts
                  .filter((a) => {
                    if (!searchQuery.trim()) return true;
                    const q = searchQuery.toLowerCase();
                    return (
                      a.filename.toLowerCase().includes(q) ||
                      (a.title && a.title.toLowerCase().includes(q)) ||
                      (a.description && a.description.toLowerCase().includes(q)) ||
                      String(a.run_id).includes(q)
                    );
                  })
                  .map((artifact) => (
                    <li key={artifact.id} className="flex items-center gap-3 px-4 py-3 hover:bg-surface-2/30 transition">
                      <div className="min-w-0 flex-1">
                        <div className="flex items-center gap-2">
                          <p className="truncate text-sm font-semibold text-ink-1">
                            {artifact.title || artifact.filename}
                          </p>
                          <span className="font-mono text-[11px] text-brand bg-brand/10 px-1.5 py-0.5 rounded border border-brand/20">
                            {artifact.filename}
                          </span>
                        </div>
                        <p className="truncate font-mono text-[10px] text-ink-3">
                          {titleCase(artifact.artifact_type)} · {formatBytes(artifact.file_size)} ·{" "}
                          {formatDateTime(artifact.created_at)}
                          {artifact.run_id ? ` · Run #${artifact.run_id}` : ""}
                        </p>
                        {artifact.description && (
                          <p className="mt-0.5 truncate text-xs text-ink-3">{artifact.description}</p>
                        )}
                      </div>
                      <Button
                        variant="secondary"
                        size="sm"
                        onClick={() => void handleDownload(artifact)}
                        loading={downloadingId === artifact.id}
                        title={`Download ${artifact.filename}`}
                      >
                        <IconDownload className="h-3.5 w-3.5" /> Download
                      </Button>
                    </li>
                  ))}
              </ul>
            )}
          </PanelBody>
        </Panel>
      )}
    </div>
  );
}