"""CogniShift Phase 7 — Safe Demo Reset Utility.

Resets only demo/simulation state in Workspace #1:
- Cleans demo runs & run events
- Cleans demo approval requests
- Cleans demo artifacts and physical generated files
- Cleans uploaded inspection reports and temporary files
- Preserves: models, authentication credentials, Phase 6 evidence, base database schema.
"""

import os
import sys
import shutil
import sqlite3
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT_DIR / "src"))

from cognishift.app.config import settings

DB_PATH = settings.database_path

def reset_demo_workspace():
    print("============================================================")
    print("  COGNISHIFT PHASE 7 — RESET DEMO WORKSPACE")
    print("============================================================")

    if not DB_PATH.exists():
        print(f"Database {DB_PATH} does not exist.")
        return

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    c = conn.cursor()

    # 1. Delete runs and associated run_events
    c.execute("SELECT id FROM agent_runs WHERE workspace_id = 1")
    run_ids = [r["id"] for r in c.fetchall()]

    if run_ids:
        placeholders = ",".join("?" for _ in run_ids)
        c.execute(f"DELETE FROM run_events WHERE run_id IN ({placeholders})", run_ids)
        c.execute(f"DELETE FROM approval_requests WHERE run_id IN ({placeholders})", run_ids)
        c.execute(f"DELETE FROM agent_runs WHERE id IN ({placeholders})", run_ids)
        print(f"  [OK] Cleaned {len(run_ids)} demo runs, associated events, and approvals.")
    else:
        print("  [OK] Zero demo runs present in Workspace #1.")

    # 2. Clean artifacts in workspace 1
    c.execute("DELETE FROM workspace_artifacts WHERE workspace_id = 1")
    print("  [OK] Cleared workspace_artifacts ledger for Workspace #1.")

    # 3. Clean uploaded inspection reports from knowledge_sources
    c.execute("SELECT id, local_path FROM knowledge_sources WHERE workspace_id = 1 AND name != 'Pump_Maintenance_SOP.pdf'")
    non_base_docs = c.fetchall()
    for doc in non_base_docs:
        sid = doc["id"]
        c.execute("DELETE FROM document_pages WHERE source_id = ?", (sid,))
        c.execute("DELETE FROM document_processing_jobs WHERE source_id = ?", (sid,))
        c.execute("DELETE FROM knowledge_sources WHERE id = ?", (sid,))
        if doc["local_path"] and os.path.exists(doc["local_path"]):
            try:
                os.remove(doc["local_path"])
            except OSError:
                pass
    print(f"  [OK] Removed {len(non_base_docs)} uploaded demo inspection reports.")

    # 4. Clean physical workspace 1 files on disk
    ws1_dir = ROOT_DIR / "data" / "workspaces" / "1"
    for sub in ["generated", "temporary"]:
        target = ws1_dir / sub
        if target.exists():
            shutil.rmtree(target, ignore_errors=True)
            target.mkdir(parents=True, exist_ok=True)
    print(f"  [OK] Purged physical temporary and generated artifacts in {ws1_dir}.")

    # 5. Reset audit events generated by demo runs
    c.execute("DELETE FROM audit_events WHERE workspace_id = 1 AND actor_id IN ('operator_sam', 'supervisor_jane', 'admin_rohit')")
    print("  [OK] Reset demo audit entries.")

    conn.commit()
    conn.close()

    print("============================================================")
    print("  DEMO WORKSPACE #1 SUCCESSFULLY RESET")
    print("  Ready for fresh rehearsal or jury evaluation.")
    print("============================================================")

if __name__ == "__main__":
    reset_demo_workspace()
